### ISSUE TITLE
Anfage

### ISSUE THREAD

**Issue by MasterRoCcO** [0xzou/drftpd3#2]
Hi can you do that in the
src / plugins / org.drftpd.commands.request / src / org / drftpd / commands / request / Request.java file to change the SimpleDateFormat sdf = new SimpleDateFormat ("MM.dd.yyyy @ HH: mm");
on
SimpleDateFormat sdf = new SimpleDateFormat ("MM-dd-yyyy @ HH: mm");

or on a setting option via conf.

Because in Europe it looks like this first comes dd then MM then yyyy comes. Therefore, this is confusing with.

then I have 3 more questions!

In linkmanager.conf under LATESTDIR you can read which section it should read! So I leave e.g. MP3 out. But a LATESTDIR is made after all. Therefore I have to enter it under sectionexclude. But now the LATESTDIR is deleted. As soon as a new one is made to you in MP3.

Can you please tell me how I do it in ircannounce.conf
# NFO:
store.path.1 = ^. + \\. nfo $
store.path.1.destination = public
store.path.1.regex = true

set that to section
so that's how
In mp3
store.path.1 = ^. + \\. nfo $
store.path.1.destination = MP3 chan
store.path.1.regex = true
TV
store.path.2 = ^. + \\. nfo $
store.path.2.destination = TV chan
store.path.2.regex = true

Is there a way to include in the nukefilter.conf approved gps. Because so far I've always done the whole thing via nuke.exempt.dirnames.regex. But the same should not always apply in the section.

And sorry for my english because I translated it with google.

Hi kannst du das in der 
src/plugins/org.drftpd.commands.request/src/org/drftpd/commands/request/Request.java Datei das ändern SimpleDateFormat sdf = new SimpleDateFormat("MM.dd.yyyy @ HH:mm");
auf 
SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy @ HH:mm");  

oder auf eine Einstellungs Möglichkeit per conf.

Denn in Europa schaut das ja so aus das erst dd kommt dann MM dann yyyy kommt. Daher ist das verwirrend mit . 

dann habe ich noch 3 fragen!

Im linkmanager.conf steht unter LATESTDIR welche section er einlesen soll! So ich lasse z.B. MP3 raus. Wird aber doch ein LATESTDIR gemacht. Daher muss ich das unter sectionexclude eintragen. Aber nun wird das  LATESTDIR gelöscht. Sobald ein neues Dir in MP3 gemacht wird.

Kannst du mir mal bitte sagen wie ich in der ircannounce.conf unter 
# NFO:
store.path.1=^.+\\.nfo$
store.path.1.destination=public
store.path.1.regex=true

das auf section einstelle
also so
In mp3
store.path.1=^.+\\.nfo$
store.path.1.destination=MP3 chan
store.path.1.regex=true
TV
store.path.2=^.+\\.nfo$
store.path.2.destination=TV chan
store.path.2.regex=true

Gibt es eine Möglichkeit in der nukefilter.conf approved gps mit einzubauen. Denn bis jetzt habe ich das ganze immer über nuke.exempt.dirnames.regex gemacht. Aber es sollten nicht immer das gleiche gelten in den  section.

Und Sorry für mein Englisch da ich es mit google übersetzt habe.

**Comment by hol4nd4** [comment]
Hello,

Just added the option to configure date format via requests.conf

https://github.com/0xzou/drftpd3/commit/b610aad9aaff98ec85b1616d9a7c0530c8ec7301

Regarding the other questions, can you create a seperated "ticket" for that ? Thanks
